package xbb.ai.erp.codegen.template;

public enum TemplateType {
    ADMIN_CONTROLLER,
    ADMIN_LIST_DTO,
    ADMIN_MAIN_DTO,
    ADMIN_SAVE_DTO,
    ADMIN_LIST_ITEM_VO,
    ADMIN_SAVE_ITEM_VO,
    ADMIN_DETAIL_VO,
    APP_SERVICE,
    APP_SERVICE_IMPL,
    APP_QUERY_SERVICE_IMPL,
    APP_SAVE_SERVICE_IMPL,
    APP_ASSEMBLER,
    APP_VALIDATOR,
    APP_QUERY_POJO,
    DOMAIN_MODEL,
    DOMAIN_REPOSITORY,
    DOMAIN_QUERY_POJO,
    PERSISTENCE_PO,
    PERSISTENCE_MAPPER,
    PERSISTENCE_CONVERTOR,
    PERSISTENCE_REPOSITORY_IMPL,
    PERSISTENCE_CONDITION_MAP_HELPER,
    MAPPER_XML
}
