package xbb.ai.erp.codegen.spec;

public enum FileSlotEnum {
    ADMIN_CONTROLLER,
    ADMIN_DTO,
    ADMIN_VO,
    APP_SERVICE,
    APP_SERVICE_IMPL,
    APP_ASSEMBLER,
    DOMAIN_MODEL,
    DOMAIN_REPOSITORY,
    PERSISTENCE_PO,
    PERSISTENCE_MAPPER,
    PERSISTENCE_CONVERTOR,
    PERSISTENCE_REPOSITORY_IMPL,
    MAPPER_XML
}
