-- 采购模块初始化 SQL
-- 生成日期：2026-07-23

CREATE TABLE IF NOT EXISTS `purchase_pending_task` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `purchase_org_id` bigint(20) NOT NULL COMMENT '采购组织ID',
  `task_no` varchar(64) NOT NULL COMMENT '任务号',
  `source_type` varchar(32) NOT NULL COMMENT '来源类型',
  `source_doc_id` bigint(20) DEFAULT NULL COMMENT '来源单据ID',
  `source_line_id` bigint(20) DEFAULT NULL COMMENT '来源行ID',
  `source_doc_no` varchar(64) DEFAULT NULL COMMENT '来源单号快照',
  `sku_id` bigint(20) NOT NULL COMMENT 'SKU ID',
  `sku_code_snapshot` varchar(64) NOT NULL COMMENT 'SKU编码快照',
  `sku_name_snapshot` varchar(128) NOT NULL COMMENT 'SKU名称快照',
  `need_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '需求数量',
  `occupied_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已占用数量',
  `generated_request_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已生成申请数量',
  `generated_order_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已生成订单数量',
  `closed_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已关闭数量',
  `suggested_vendor_id` bigint(20) DEFAULT NULL COMMENT '建议供应商ID',
  `suggested_delivery_date` bigint(20) DEFAULT NULL COMMENT '建议交期',
  `priority_level` int(11) NOT NULL DEFAULT '0' COMMENT '优先级',
  `task_status` varchar(32) NOT NULL COMMENT '任务状态',
  `sales_linked_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否以销定购挂钩',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pending_task_no` (`corpid`, `task_no`, `del`),
  KEY `idx_pending_source` (`corpid`, `source_type`, `source_doc_id`, `source_line_id`, `del`),
  KEY `idx_pending_workbench` (`corpid`, `purchase_org_id`, `task_status`, `priority_level`, `del`),
  KEY `idx_pending_sku` (`corpid`, `sku_id`, `task_status`, `del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='待采购任务表';

CREATE TABLE IF NOT EXISTS `purchase_request` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `purchase_org_id` bigint(20) NOT NULL COMMENT '采购组织ID',
  `request_no` varchar(64) NOT NULL COMMENT '申请单号',
  `request_dept_id` bigint(20) DEFAULT NULL COMMENT '申请部门ID',
  `applicant_id` varchar(50) DEFAULT NULL COMMENT '申请人ID',
  `source_type` varchar(32) NOT NULL COMMENT '需求来源类型',
  `source_no` varchar(64) DEFAULT NULL COMMENT '来源单号',
  `suggested_vendor_id` bigint(20) DEFAULT NULL COMMENT '建议供应商ID',
  `suggested_delivery_date` bigint(20) DEFAULT NULL COMMENT '建议交期',
  `biz_status` varchar(32) NOT NULL COMMENT '业务状态',
  `approval_status` varchar(32) NOT NULL COMMENT '审批状态',
  `gross_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '估算含税金额',
  `net_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '估算未税金额',
  `tax_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '估算税额',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_request_no` (`corpid`, `request_no`, `del`),
  KEY `idx_request_org_status` (`corpid`, `purchase_org_id`, `biz_status`, `approval_status`, `del`),
  KEY `idx_request_source` (`corpid`, `source_type`, `source_no`, `del`),
  KEY `idx_request_time` (`corpid`, `add_time`, `del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购申请单头表';

CREATE TABLE IF NOT EXISTS `purchase_request_item` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `request_id` bigint(20) NOT NULL COMMENT '申请单头ID',
  `line_no` int(11) NOT NULL COMMENT '行号',
  `sku_id` bigint(20) NOT NULL COMMENT 'SKU ID',
  `sku_code_snapshot` varchar(64) NOT NULL COMMENT 'SKU编码快照',
  `sku_name_snapshot` varchar(128) NOT NULL COMMENT 'SKU名称快照',
  `spec_snapshot` varchar(255) DEFAULT NULL COMMENT '规格快照',
  `purchase_unit_id` bigint(20) NOT NULL COMMENT '采购单位ID',
  `request_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '申请数量',
  `reserved_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已占用下推量',
  `executed_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已正式下推量',
  `closed_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已关闭量',
  `suggested_vendor_id` bigint(20) DEFAULT NULL COMMENT '建议供应商ID',
  `suggested_delivery_date` bigint(20) DEFAULT NULL COMMENT '建议交期',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_request_line` (`request_id`, `line_no`, `del`),
  KEY `idx_request_item_sku` (`corpid`, `sku_id`, `del`),
  KEY `idx_request_item_qty` (`corpid`, `request_id`, `reserved_qty`, `executed_qty`, `closed_qty`, `del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购申请单行表';

CREATE TABLE IF NOT EXISTS `purchase_order` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `purchase_org_id` bigint(20) NOT NULL COMMENT '采购组织ID',
  `order_no` varchar(64) NOT NULL COMMENT '订单号',
  `vendor_id` bigint(20) NOT NULL COMMENT '供应商ID',
  `vendor_name_snapshot` varchar(128) NOT NULL COMMENT '供应商名称快照',
  `purchaser_id` varchar(50) DEFAULT NULL COMMENT '采购员ID',
  `purchaser_name_snapshot` varchar(50) DEFAULT NULL COMMENT '采购员名称快照',
  `warehouse_id` bigint(20) DEFAULT NULL COMMENT '默认收货仓库ID',
  `warehouse_name_snapshot` varchar(128) DEFAULT NULL COMMENT '仓库名称快照',
  `settlement_method_id` bigint(20) DEFAULT NULL COMMENT '结算方式ID',
  `settlement_method_snapshot` varchar(128) DEFAULT NULL COMMENT '结算方式快照',
  `payment_term_snapshot` varchar(255) DEFAULT NULL COMMENT '付款条件快照',
  `currency_code` varchar(16) NOT NULL COMMENT '币种',
  `delivery_date` bigint(20) DEFAULT NULL COMMENT '交货日期',
  `source_type` varchar(32) DEFAULT NULL COMMENT '来源类型',
  `source_no` varchar(64) DEFAULT NULL COMMENT '来源单号',
  `sales_linked_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否以销定购',
  `biz_status` varchar(32) NOT NULL COMMENT '业务状态',
  `approval_status` varchar(32) NOT NULL COMMENT '审批状态',
  `execution_status` varchar(32) NOT NULL COMMENT '执行状态',
  `receipt_status` varchar(32) NOT NULL COMMENT '收料状态',
  `inbound_status` varchar(32) NOT NULL COMMENT '入库状态',
  `payable_status` varchar(32) NOT NULL COMMENT '应付状态',
  `invoice_status` varchar(32) NOT NULL COMMENT '收票状态',
  `payment_status` varchar(32) NOT NULL COMMENT '付款状态',
  `gross_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '含税金额',
  `net_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '未税金额',
  `tax_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '税额',
  `inbounded_qty_summary` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已入库数量摘要',
  `uninbounded_qty_summary` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '未入库数量摘要',
  `closed_qty_summary` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已关闭数量摘要',
  `payable_amount_summary` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已确认应付金额',
  `paid_amount_summary` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已付金额',
  `invoiced_amount_summary` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已收票金额',
  `last_inbound_time` bigint(20) DEFAULT NULL COMMENT '最近入库时间',
  `last_payable_time` bigint(20) DEFAULT NULL COMMENT '最近应付确认时间',
  `period_locked_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '期间锁定标志',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_order_no` (`corpid`, `order_no`, `del`),
  KEY `idx_purchase_order_vendor` (`corpid`, `vendor_id`, `del`),
  KEY `idx_purchase_order_org_status` (`corpid`, `purchase_org_id`, `biz_status`, `approval_status`, `execution_status`, `del`),
  KEY `idx_purchase_order_finance_status` (`corpid`, `payable_status`, `invoice_status`, `payment_status`, `del`),
  KEY `idx_purchase_order_delivery` (`corpid`, `delivery_date`, `del`),
  KEY `idx_purchase_order_time` (`corpid`, `add_time`, `del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购订单头表';

CREATE TABLE IF NOT EXISTS `purchase_order_item` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `order_id` bigint(20) NOT NULL COMMENT '订单头ID',
  `line_no` int(11) NOT NULL COMMENT '行号',
  `sku_id` bigint(20) NOT NULL COMMENT 'SKU ID',
  `sku_code_snapshot` varchar(64) NOT NULL COMMENT 'SKU编码快照',
  `sku_name_snapshot` varchar(128) NOT NULL COMMENT 'SKU名称快照',
  `spec_snapshot` varchar(255) DEFAULT NULL COMMENT '规格快照',
  `purchase_unit_id` bigint(20) NOT NULL COMMENT '采购单位ID',
  `warehouse_id` bigint(20) DEFAULT NULL COMMENT '行级收货仓库ID',
  `order_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '订单数量',
  `received_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已收料数量',
  `inbounded_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已入库数量',
  `closed_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已关闭数量',
  `returned_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已退料数量',
  `gross_price` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '含税单价',
  `net_price` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '未税单价',
  `tax_rate` decimal(8,4) NOT NULL DEFAULT '0.0000' COMMENT '税率',
  `tax_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '税额',
  `gross_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '含税金额',
  `net_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '未税金额',
  `payable_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已确认应付金额',
  `paid_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已付金额',
  `invoiced_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已收票金额',
  `is_gift` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否赠品',
  `delivery_plan_snapshot` varchar(500) DEFAULT NULL COMMENT '交货计划快照',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_order_line` (`order_id`, `line_no`, `del`),
  KEY `idx_purchase_order_item_sku` (`corpid`, `sku_id`, `del`),
  KEY `idx_purchase_order_item_exec` (`corpid`, `order_id`, `inbounded_qty`, `closed_qty`, `del`),
  KEY `idx_purchase_order_item_wh` (`corpid`, `warehouse_id`, `del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购订单行表';

CREATE TABLE IF NOT EXISTS `purchase_source_relation` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `source_doc_type` varchar(32) NOT NULL COMMENT '来源单据类型',
  `source_doc_id` bigint(20) NOT NULL COMMENT '来源单据ID',
  `source_line_id` bigint(20) DEFAULT NULL COMMENT '来源行ID',
  `target_doc_type` varchar(32) NOT NULL COMMENT '目标单据类型',
  `target_doc_id` bigint(20) NOT NULL COMMENT '目标单据ID',
  `target_line_id` bigint(20) DEFAULT NULL COMMENT '目标行ID',
  `source_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '来源总量',
  `reserved_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已占用量',
  `executed_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已执行量',
  `closed_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已关闭量',
  `reversed_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已逆向回退量',
  `relation_status` varchar(32) NOT NULL COMMENT '关系状态',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  KEY `idx_purchase_source_doc` (`corpid`, `source_doc_type`, `source_doc_id`, `source_line_id`, `del`),
  KEY `idx_purchase_target_doc` (`corpid`, `target_doc_type`, `target_doc_id`, `target_line_id`, `del`),
  KEY `idx_purchase_relation_status` (`corpid`, `relation_status`, `del`),
  UNIQUE KEY `uk_purchase_source_target` (`corpid`, `source_line_id`, `target_line_id`, `target_doc_type`, `del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购来源关系表';
