CREATE TABLE `product_category` (
  `id` bigint NOT NULL,
  `corpid` varchar(50) NOT NULL,
  `category_code` varchar(64) NOT NULL,
  `category_name` varchar(128) NOT NULL,
  `parent_id` bigint NOT NULL,
  `category_level` int NOT NULL,
  `sort_no` int NOT NULL,
  `enable_status` tinyint NOT NULL,
  `del` tinyint NOT NULL,
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(50) NOT NULL,
  `modify_id` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_category_code` (`corpid`, `category_code`, `del`),
  KEY `idx_category_parent` (`corpid`, `parent_id`, `del`),
  KEY `idx_category_status` (`corpid`, `enable_status`, `del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `product_brand` (
  `id` bigint NOT NULL,
  `corpid` varchar(50) NOT NULL,
  `brand_code` varchar(64) NOT NULL,
  `brand_name` varchar(128) NOT NULL,
  `sort_no` int DEFAULT NULL,
  `enable_status` tinyint NOT NULL,
  `del` tinyint NOT NULL,
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(50) NOT NULL,
  `modify_id` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_brand_code` (`corpid`, `brand_code`, `del`),
  KEY `idx_brand_status` (`corpid`, `enable_status`, `del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `product_unit` (
  `id` bigint NOT NULL,
  `corpid` varchar(50) NOT NULL,
  `unit_code` varchar(64) NOT NULL,
  `unit_name` varchar(64) NOT NULL,
  `precision_num` int NOT NULL,
  `enable_status` tinyint NOT NULL,
  `del` tinyint NOT NULL,
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(50) NOT NULL,
  `modify_id` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unit_code` (`corpid`, `unit_code`, `del`),
  KEY `idx_unit_status` (`corpid`, `enable_status`, `del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `product_spu` (
  `id` bigint NOT NULL,
  `corpid` varchar(50) NOT NULL,
  `spu_code` varchar(64) NOT NULL,
  `spu_name` varchar(256) NOT NULL,
  `category_id` bigint NOT NULL,
  `brand_id` bigint DEFAULT NULL,
  `product_type` varchar(32) NOT NULL,
  `enable_spec` tinyint NOT NULL,
  `description` varchar(1024) DEFAULT NULL,
  `image_url` varchar(512) DEFAULT NULL,
  `enable_status` tinyint NOT NULL,
  `del` tinyint NOT NULL,
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(50) NOT NULL,
  `modify_id` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_spu_code` (`corpid`, `spu_code`, `del`),
  KEY `idx_spu_category` (`corpid`, `category_id`, `del`),
  KEY `idx_spu_brand` (`corpid`, `brand_id`, `del`),
  KEY `idx_spu_type` (`corpid`, `product_type`, `del`),
  KEY `idx_spu_status` (`corpid`, `enable_status`, `del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `product_sku` (
  `id` bigint NOT NULL,
  `corpid` varchar(50) NOT NULL,
  `spu_id` bigint NOT NULL,
  `sku_code` varchar(64) NOT NULL,
  `sku_name` varchar(256) NOT NULL,
  `mnemonic_code` varchar(64) DEFAULT NULL,
  `main_barcode` varchar(64) DEFAULT NULL,
  `spec_signature` varchar(256) DEFAULT NULL,
  `spec_snapshot` text,
  `can_purchase` tinyint NOT NULL,
  `can_sale` tinyint NOT NULL,
  `can_inventory` tinyint NOT NULL,
  `can_produce` tinyint NOT NULL,
  `enable_status` tinyint NOT NULL,
  `listing_status` tinyint NOT NULL,
  `weight` decimal(18,6) DEFAULT NULL,
  `volume` decimal(18,6) DEFAULT NULL,
  `ext_json` text,
  `del` tinyint NOT NULL,
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(50) NOT NULL,
  `modify_id` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku_code` (`corpid`, `sku_code`, `del`),
  UNIQUE KEY `uk_sku_barcode` (`corpid`, `main_barcode`, `del`),
  UNIQUE KEY `uk_spu_spec_signature` (`corpid`, `spu_id`, `spec_signature`, `del`),
  KEY `idx_sku_spu` (`corpid`, `spu_id`, `del`),
  KEY `idx_sku_status` (`corpid`, `enable_status`, `del`),
  KEY `idx_sku_listing` (`corpid`, `listing_status`, `del`),
  KEY `idx_sku_purchase` (`corpid`, `can_purchase`, `enable_status`, `del`),
  KEY `idx_sku_sale` (`corpid`, `can_sale`, `listing_status`, `enable_status`, `del`),
  KEY `idx_sku_inventory` (`corpid`, `can_inventory`, `enable_status`, `del`),
  KEY `idx_sku_produce` (`corpid`, `can_produce`, `enable_status`, `del`),
  KEY `idx_sku_mnemonic` (`corpid`, `mnemonic_code`, `del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `warehouse` (
  `id` bigint NOT NULL,
  `corpid` varchar(50) NOT NULL,
  `biz_org_id` bigint NOT NULL,
  `warehouse_code` varchar(64) NOT NULL,
  `warehouse_name` varchar(128) NOT NULL,
  `warehouse_type` varchar(32) NOT NULL,
  `enable_status` tinyint NOT NULL,
  `address` varchar(255) DEFAULT NULL,
  `manager_id` varchar(50) DEFAULT NULL,
  `biz_status` varchar(32) NOT NULL,
  `del` tinyint NOT NULL,
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(50) NOT NULL,
  `modify_id` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_warehouse_code` (`corpid`, `warehouse_code`, `del`),
  KEY `idx_warehouse_list` (`corpid`, `biz_org_id`, `enable_status`, `del`),
  KEY `idx_warehouse_name` (`corpid`, `warehouse_name`, `del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
