CREATE TABLE `customer` (
  `id` BIGINT NOT NULL,
  `corpid` VARCHAR(50) NOT NULL,
  `customer_code` VARCHAR(64) NOT NULL,
  `customer_name` VARCHAR(128) NOT NULL,
  `customer_short_name` VARCHAR(128) DEFAULT NULL,
  `customer_category` VARCHAR(32) NOT NULL,
  `region_code` VARCHAR(32) DEFAULT NULL,
  `owner_sales_id` VARCHAR(50) DEFAULT NULL,
  `owner_sales_name_snapshot` VARCHAR(50) DEFAULT NULL,
  `biz_status` VARCHAR(32) NOT NULL,
  `ref_status` VARCHAR(32) NOT NULL,
  `default_contact_id` BIGINT DEFAULT NULL,
  `default_address_id` BIGINT DEFAULT NULL,
  `remark` VARCHAR(500) DEFAULT NULL,
  `del` TINYINT NOT NULL DEFAULT 0,
  `add_time` BIGINT NOT NULL,
  `update_time` BIGINT NOT NULL,
  `creator_id` VARCHAR(50) NOT NULL,
  `modify_id` VARCHAR(50) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_corpid_customer_code` (`corpid`, `customer_code`),
  KEY `idx_corpid_biz_status_update_time` (`corpid`, `biz_status`, `update_time`),
  KEY `idx_corpid_ref_status_update_time` (`corpid`, `ref_status`, `update_time`),
  KEY `idx_corpid_owner_sales` (`corpid`, `owner_sales_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `customer_contact` (
  `id` BIGINT NOT NULL,
  `corpid` VARCHAR(50) NOT NULL,
  `customer_id` BIGINT NOT NULL,
  `contact_name` VARCHAR(64) NOT NULL,
  `mobile` VARCHAR(32) DEFAULT NULL,
  `phone` VARCHAR(32) DEFAULT NULL,
  `email` VARCHAR(128) DEFAULT NULL,
  `position_name` VARCHAR(64) DEFAULT NULL,
  `default_flag` TINYINT NOT NULL DEFAULT 0,
  `biz_status` VARCHAR(32) NOT NULL,
  `remark` VARCHAR(255) DEFAULT NULL,
  `del` TINYINT NOT NULL DEFAULT 0,
  `add_time` BIGINT NOT NULL,
  `update_time` BIGINT NOT NULL,
  `creator_id` VARCHAR(50) NOT NULL,
  `modify_id` VARCHAR(50) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_corpid_customer_id` (`corpid`, `customer_id`),
  KEY `idx_corpid_customer_default_flag` (`corpid`, `customer_id`, `default_flag`),
  KEY `idx_corpid_mobile` (`corpid`, `mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `customer_address` (
  `id` BIGINT NOT NULL,
  `corpid` VARCHAR(50) NOT NULL,
  `customer_id` BIGINT NOT NULL,
  `address_type` VARCHAR(32) NOT NULL,
  `receiver_name` VARCHAR(64) DEFAULT NULL,
  `receiver_mobile` VARCHAR(32) DEFAULT NULL,
  `province_code` VARCHAR(32) DEFAULT NULL,
  `city_code` VARCHAR(32) DEFAULT NULL,
  `district_code` VARCHAR(32) DEFAULT NULL,
  `detail_address` VARCHAR(255) NOT NULL,
  `postal_code` VARCHAR(16) DEFAULT NULL,
  `default_flag` TINYINT NOT NULL DEFAULT 0,
  `biz_status` VARCHAR(32) NOT NULL,
  `del` TINYINT NOT NULL DEFAULT 0,
  `add_time` BIGINT NOT NULL,
  `update_time` BIGINT NOT NULL,
  `creator_id` VARCHAR(50) NOT NULL,
  `modify_id` VARCHAR(50) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_corpid_customer_id` (`corpid`, `customer_id`),
  KEY `idx_corpid_customer_default_flag` (`corpid`, `customer_id`, `default_flag`),
  KEY `idx_corpid_address_type` (`corpid`, `address_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `customer_bank_account` (
  `id` BIGINT NOT NULL,
  `corpid` VARCHAR(50) NOT NULL,
  `customer_id` BIGINT NOT NULL,
  `account_name` VARCHAR(128) NOT NULL,
  `bank_name` VARCHAR(128) NOT NULL,
  `account_no` VARCHAR(64) NOT NULL,
  `account_usage` VARCHAR(64) DEFAULT NULL,
  `default_flag` TINYINT NOT NULL DEFAULT 0,
  `biz_status` VARCHAR(32) NOT NULL,
  `remark` VARCHAR(255) DEFAULT NULL,
  `del` TINYINT NOT NULL DEFAULT 0,
  `add_time` BIGINT NOT NULL,
  `update_time` BIGINT NOT NULL,
  `creator_id` VARCHAR(50) NOT NULL,
  `modify_id` VARCHAR(50) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_corpid_customer_id` (`corpid`, `customer_id`),
  KEY `idx_corpid_customer_default_flag` (`corpid`, `customer_id`, `default_flag`),
  KEY `idx_corpid_account_no` (`corpid`, `account_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `customer_invoice_profile` (
  `id` BIGINT NOT NULL,
  `corpid` VARCHAR(50) NOT NULL,
  `customer_id` BIGINT NOT NULL,
  `invoice_title` VARCHAR(128) NOT NULL,
  `tax_no` VARCHAR(64) NOT NULL,
  `address_phone` VARCHAR(128) DEFAULT NULL,
  `bank_name` VARCHAR(128) DEFAULT NULL,
  `bank_account_no` VARCHAR(64) DEFAULT NULL,
  `default_flag` TINYINT NOT NULL DEFAULT 0,
  `biz_status` VARCHAR(32) NOT NULL,
  `remark` VARCHAR(255) DEFAULT NULL,
  `del` TINYINT NOT NULL DEFAULT 0,
  `add_time` BIGINT NOT NULL,
  `update_time` BIGINT NOT NULL,
  `creator_id` VARCHAR(50) NOT NULL,
  `modify_id` VARCHAR(50) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_corpid_customer_id` (`corpid`, `customer_id`),
  KEY `idx_corpid_customer_default_flag` (`corpid`, `customer_id`, `default_flag`),
  KEY `idx_corpid_tax_no` (`corpid`, `tax_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
