-- 资金往来业务表设计
--
-- 适用范围：采购发票、应付款、付款单、预付款、付款核销及统一资金流水。
-- 执行事实源：实施时在 xbb-erp-app-admin/src/main/resources/db/migration/ 创建新的 Flyway 迁移。
-- 本文件是可读设计 SQL，不应直接作为已上线环境的迁移脚本执行。

CREATE TABLE `purchase_invoice` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `corpid` varchar(64) NOT NULL COMMENT '租户ID',
    `invoice_no` varchar(64) NOT NULL COMMENT '采购发票编号',
    `supplier_invoice_no` varchar(128) DEFAULT NULL COMMENT '供应商发票号码',
    `supplier_id` bigint(20) NOT NULL COMMENT '供应商ID',
    `invoice_date` bigint(20) NOT NULL COMMENT '发票日期',
    `due_date` bigint(20) DEFAULT NULL COMMENT '应付到期日',
    `payment_term` varchar(64) DEFAULT NULL COMMENT '付款条件',
    `untaxed_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '未税金额',
    `tax_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '税额',
    `amount` decimal(18,2) NOT NULL COMMENT '含税总金额',
    `invoice_type` varchar(32) NOT NULL DEFAULT 'PURCHASE' COMMENT '类型：PURCHASE、PURCHASE_RED',
    `status` varchar(32) NOT NULL COMMENT '状态：DRAFT、AUDITED、POSTED、VOIDED、RED_FLUSHED',
    `audit_status` tinyint(2) NOT NULL DEFAULT '0' COMMENT '审核状态：0待审核，1审核中，2已审核，3已拒绝',
    `audit_time` bigint(20) DEFAULT NULL COMMENT '审核时间',
    `posted_time` bigint(20) DEFAULT NULL COMMENT '过账时间',
    `original_invoice_id` bigint(20) DEFAULT NULL COMMENT '原采购发票ID，红冲时必填',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `del` tinyint(2) NOT NULL DEFAULT '0',
    `add_time` bigint(20) NOT NULL,
    `update_time` bigint(20) NOT NULL,
    `creator_id` varchar(64) NOT NULL,
    `modify_id` varchar(64) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_purchase_invoice_no` (`corpid`, `invoice_no`),
    KEY `idx_purchase_invoice_supplier_date` (`corpid`, `supplier_id`, `invoice_date`),
    KEY `idx_purchase_invoice_status_due_date` (`corpid`, `status`, `due_date`),
    KEY `idx_purchase_invoice_supplier_invoice_no` (`corpid`, `supplier_id`, `supplier_invoice_no`),
    KEY `idx_purchase_invoice_original` (`corpid`, `original_invoice_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购发票';

CREATE TABLE `purchase_invoice_line` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `corpid` varchar(64) NOT NULL COMMENT '租户ID',
    `purchase_invoice_id` bigint(20) NOT NULL COMMENT '采购发票ID',
    `line_no` int(11) NOT NULL COMMENT '行号',
    `product_id` bigint(20) DEFAULT NULL COMMENT '商品或服务ID',
    `product_name` varchar(255) NOT NULL COMMENT '商品或服务名称快照',
    `specification` varchar(255) DEFAULT NULL COMMENT '规格型号快照',
    `unit_id` bigint(20) DEFAULT NULL COMMENT '单位ID',
    `quantity` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '数量',
    `unit_price` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '未税单价',
    `tax_rate` decimal(8,4) NOT NULL DEFAULT '0.0000' COMMENT '税率',
    `untaxed_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '未税金额',
    `tax_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '税额',
    `amount` decimal(18,2) NOT NULL COMMENT '含税金额',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `del` tinyint(2) NOT NULL DEFAULT '0',
    `add_time` bigint(20) NOT NULL,
    `update_time` bigint(20) NOT NULL,
    `creator_id` varchar(64) NOT NULL,
    `modify_id` varchar(64) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_purchase_invoice_line_no` (`corpid`, `purchase_invoice_id`, `line_no`),
    KEY `idx_purchase_invoice_line_invoice` (`corpid`, `purchase_invoice_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购发票明细';

CREATE TABLE `purchase_invoice_business_ref` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `corpid` varchar(64) NOT NULL COMMENT '租户ID',
    `purchase_invoice_id` bigint(20) NOT NULL COMMENT '采购发票ID',
    `ref_type` varchar(32) NOT NULL COMMENT '归属类型：PURCHASE_ORDER、PURCHASE_INBOUND、MANUAL',
    `ref_id` bigint(20) NOT NULL COMMENT '归属业务对象ID',
    `amount` decimal(18,2) DEFAULT NULL COMMENT '归属金额',
    `del` tinyint(2) NOT NULL DEFAULT '0',
    `add_time` bigint(20) NOT NULL,
    `update_time` bigint(20) NOT NULL,
    `creator_id` varchar(64) NOT NULL,
    `modify_id` varchar(64) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_purchase_invoice_business_ref` (`corpid`, `purchase_invoice_id`, `ref_type`, `ref_id`),
    KEY `idx_purchase_invoice_business_ref_target` (`corpid`, `ref_type`, `ref_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购发票业务归属关系';

CREATE TABLE `purchase_invoice_line_source` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `corpid` varchar(64) NOT NULL COMMENT '租户ID',
    `purchase_invoice_line_id` bigint(20) NOT NULL COMMENT '采购发票明细ID',
    `source_type` varchar(32) NOT NULL COMMENT '来源类型：PURCHASE_ORDER_LINE、PURCHASE_INBOUND_LINE、MANUAL',
    `source_id` bigint(20) DEFAULT NULL COMMENT '来源表头ID',
    `source_line_id` bigint(20) DEFAULT NULL COMMENT '来源明细ID',
    `quantity` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '本次开票数量',
    `untaxed_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '本次未税金额',
    `tax_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '本次税额',
    `amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '本次含税金额',
    `del` tinyint(2) NOT NULL DEFAULT '0',
    `add_time` bigint(20) NOT NULL,
    `update_time` bigint(20) NOT NULL,
    `creator_id` varchar(64) NOT NULL,
    `modify_id` varchar(64) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_purchase_invoice_line_source_invoice_line` (`corpid`, `purchase_invoice_line_id`),
    KEY `idx_purchase_invoice_line_source_source` (`corpid`, `source_type`, `source_id`, `source_line_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购发票明细来源及开票占用记录';

CREATE TABLE `payable` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `corpid` varchar(64) NOT NULL COMMENT '租户ID',
    `payable_no` varchar(64) NOT NULL COMMENT '应付开放项编号',
    `supplier_id` bigint(20) NOT NULL COMMENT '供应商ID',
    `source_type` varchar(32) NOT NULL COMMENT '来源：PURCHASE_INVOICE、OPENING_BALANCE、MANUAL_ADJUSTMENT',
    `source_invoice_id` bigint(20) DEFAULT NULL COMMENT '来源采购发票ID',
    `opening_batch_id` bigint(20) DEFAULT NULL COMMENT '期初导入批次ID',
    `payable_date` bigint(20) NOT NULL COMMENT '应付确认日期',
    `due_date` bigint(20) DEFAULT NULL COMMENT '到期日',
    `amount` decimal(18,2) NOT NULL COMMENT '初始应付金额',
    `written_off_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已核销金额',
    `remaining_amount` decimal(18,2) NOT NULL COMMENT '未核销应付余额',
    `status` tinyint(2) NOT NULL COMMENT '状态：未核销、部分核销、已核销、已关闭',
    `audit_status` tinyint(2) NOT NULL DEFAULT '0' COMMENT '审核状态：0待审核，1审核中，2已审核，3已拒绝',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `del` tinyint(2) NOT NULL DEFAULT '0',
    `add_time` bigint(20) NOT NULL,
    `update_time` bigint(20) NOT NULL,
    `creator_id` varchar(64) NOT NULL,
    `modify_id` varchar(64) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_payable_no` (`corpid`, `payable_no`),
    UNIQUE KEY `uk_payable_invoice` (`corpid`, `source_invoice_id`),
    KEY `idx_payable_supplier_status` (`corpid`, `supplier_id`, `status`, `due_date`),
    KEY `idx_payable_source` (`corpid`, `source_type`, `source_invoice_id`),
    KEY `idx_payable_audit_status` (`corpid`, `audit_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应付开放项';

CREATE TABLE `payment` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `corpid` varchar(64) NOT NULL COMMENT '租户ID',
    `payment_no` varchar(64) NOT NULL COMMENT '付款单编号',
    `supplier_id` bigint(20) NOT NULL COMMENT '供应商ID',
    `payment_date` bigint(20) NOT NULL COMMENT '付款日期',
    `amount` decimal(18,2) NOT NULL COMMENT '实际付款金额',
    `written_off_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已核销金额',
    `remaining_amount` decimal(18,2) NOT NULL COMMENT '未核销付款余额',
    `payment_type` varchar(32) NOT NULL DEFAULT 'SUPPLIER_PAYMENT' COMMENT '付款类型：SUPPLIER_PAYMENT、ADVANCE_PAYMENT、OPENING_PAYMENT',
    `payment_method` varchar(32) DEFAULT NULL COMMENT '付款方式摘要',
    `bank_account_id` bigint(20) DEFAULT NULL COMMENT '付款资金账户ID摘要',
    `bank_transaction_no` varchar(128) DEFAULT NULL COMMENT '银行流水号或第三方交易号摘要',
    `status` tinyint(2) NOT NULL COMMENT '状态：未核销、部分核销、已核销、已关闭',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `del` tinyint(2) NOT NULL DEFAULT '0',
    `add_time` bigint(20) NOT NULL,
    `update_time` bigint(20) NOT NULL,
    `creator_id` varchar(64) NOT NULL,
    `modify_id` varchar(64) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_payment_no` (`corpid`, `payment_no`),
    KEY `idx_payment_supplier_date` (`corpid`, `supplier_id`, `payment_date`),
    KEY `idx_payment_supplier_status` (`corpid`, `supplier_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商付款开放项，含普通付款和预付款';

CREATE TABLE `payment_detail` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `corpid` varchar(64) NOT NULL COMMENT '租户ID',
    `payment_id` bigint(20) NOT NULL COMMENT '付款单ID',
    `bank_account_id` bigint(20) NOT NULL COMMENT '资金账户ID，关联fund_account',
    `payment_method` varchar(32) NOT NULL COMMENT '付款方式',
    `amount` decimal(18,2) NOT NULL COMMENT '付款金额',
    `handling_fee` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '手续费',
    `transaction_no` varchar(128) NOT NULL DEFAULT '' COMMENT '交易号或票据号',
    `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '付款备注',
    `sort_no` int(11) NOT NULL DEFAULT '0' COMMENT '排序号',
    `del` tinyint(2) NOT NULL DEFAULT '0',
    `add_time` bigint(20) NOT NULL,
    `update_time` bigint(20) NOT NULL,
    `creator_id` varchar(64) NOT NULL,
    `modify_id` varchar(64) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_payment_detail_payment` (`corpid`, `payment_id`, `del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商付款明细';

CREATE TABLE `payment_writeoff` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `corpid` varchar(64) NOT NULL COMMENT '租户ID',
    `writeoff_no` varchar(64) NOT NULL COMMENT '核销批次号',
    `payment_id` bigint(20) NOT NULL COMMENT '付款单ID',
    `payable_id` bigint(20) NOT NULL COMMENT '应付开放项ID',
    `writeoff_date` bigint(20) NOT NULL COMMENT '核销日期',
    `amount` decimal(18,2) NOT NULL COMMENT '核销金额',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `creator_id` varchar(64) NOT NULL,
    `modify_id` varchar(64) NOT NULL,
    `del` tinyint(2) NOT NULL DEFAULT '0',
    `add_time` bigint(20) NOT NULL,
    `update_time` bigint(20) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_payment_writeoff_no` (`corpid`, `writeoff_no`, `payment_id`, `payable_id`),
    KEY `idx_payment_writeoff_payment` (`corpid`, `payment_id`),
    KEY `idx_payment_writeoff_payable` (`corpid`, `payable_id`),
    KEY `idx_payment_writeoff_date` (`corpid`, `writeoff_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商预付款与应付核销记录';

CREATE TABLE `fund_transaction` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `corpid` varchar(64) NOT NULL COMMENT '租户ID',
    `transaction_no` varchar(64) NOT NULL COMMENT '系统资金流水号',
    `transaction_date` bigint(20) NOT NULL COMMENT '资金生效日期',
    `direction` varchar(8) NOT NULL COMMENT '方向：IN收入，OUT支出',
    `bank_account_id` bigint(20) NOT NULL COMMENT '资金账户ID，关联fund_account',
    `counterparty_type` varchar(32) NOT NULL COMMENT '往来对象类型：CUSTOMER、SUPPLIER',
    `counterparty_id` bigint(20) NOT NULL COMMENT '往来对象ID',
    `business_type` varchar(32) NOT NULL COMMENT '业务类型：RECEIPT、PAYMENT',
    `business_id` bigint(20) NOT NULL COMMENT '来源业务主表ID',
    `business_no` varchar(64) NOT NULL COMMENT '来源业务单号快照',
    `business_detail_id` bigint(20) NOT NULL COMMENT '来源收付款明细ID',
    `currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '资金账户币别快照',
    `amount` decimal(18,2) NOT NULL COMMENT '业务收付金额',
    `handling_fee` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '手续费',
    `cash_amount` decimal(18,2) NOT NULL COMMENT '账户实际变动绝对额',
    `entry_type` varchar(16) NOT NULL DEFAULT 'NORMAL' COMMENT '分录类型：NORMAL、REVERSAL',
    `source_transaction_id` bigint(20) DEFAULT NULL COMMENT '原资金流水ID，冲正时必填',
    `status` varchar(16) NOT NULL DEFAULT 'POSTED' COMMENT '状态：POSTED、REVERSED',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `del` tinyint(2) NOT NULL DEFAULT '0',
    `add_time` bigint(20) NOT NULL,
    `update_time` bigint(20) NOT NULL,
    `creator_id` varchar(64) NOT NULL,
    `modify_id` varchar(64) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_fund_transaction_no` (`corpid`, `transaction_no`),
    UNIQUE KEY `uk_fund_transaction_source` (`corpid`, `business_type`, `business_detail_id`, `entry_type`),
    KEY `idx_fund_transaction_account_date` (`corpid`, `bank_account_id`, `transaction_date`),
    KEY `idx_fund_transaction_direction_date` (`corpid`, `direction`, `transaction_date`),
    KEY `idx_fund_transaction_business` (`corpid`, `business_type`, `business_id`),
    KEY `idx_fund_transaction_counterparty` (`corpid`, `counterparty_type`, `counterparty_id`, `transaction_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资金账户收支流水';
