CREATE TABLE `sales_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `corpid` varchar(64) NOT NULL COMMENT '租户ID',
  `order_no` varchar(64) NOT NULL,
  `customer_id` bigint(20) NOT NULL,
  `customer_name` varchar(128) NOT NULL,
  `warehouse_id` bigint(20) NOT NULL,
  `order_date` bigint(20) NOT NULL,
  `delivery_date` bigint(20) DEFAULT NULL,
  `total_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `status` varchar(20) NOT NULL DEFAULT 'DRAFT',
  `remark` varchar(255) DEFAULT NULL,
  `del` tinyint(2) NOT NULL DEFAULT '0',
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(64) NOT NULL,
  `modify_id` varchar(64) NOT NULL,
  `audit_status` tinyint(2) DEFAULT NULL,
  `outbound_status` tinyint(2) DEFAULT NULL,
  `receipt_status` tinyint(2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_order_no` (`corpid`,`order_no`),
  KEY `idx_sales_order_customer` (`corpid`,`customer_id`,`order_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售订单头';

CREATE TABLE `sales_order_item` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `corpid` varchar(64) NOT NULL COMMENT '租户ID',
  `sales_order_id` bigint(20) NOT NULL,
  `line_no` int(11) NOT NULL,
  `sku_id` bigint(20) NOT NULL,
  `sku_code` varchar(64) NOT NULL,
  `sku_name` varchar(128) NOT NULL,
  `specification` varchar(128) DEFAULT NULL,
  `unit_name` varchar(32) NOT NULL,
  `qty` decimal(18,6) NOT NULL,
  `delivered_qty` decimal(18,6) NOT NULL DEFAULT '0.000000',
  `unit_price` decimal(18,6) NOT NULL,
  `tax_rate` decimal(8,4) NOT NULL DEFAULT '0.0000',
  `amount` decimal(18,2) NOT NULL,
  `del` tinyint(2) NOT NULL DEFAULT '0',
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(64) NOT NULL,
  `modify_id` varchar(64) NOT NULL,
  `outbound_status` tinyint(2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_order_line` (`sales_order_id`,`line_no`),
  KEY `idx_sales_order_item_sku` (`corpid`,`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售订单行';
