CREATE TABLE `receipt` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `corpid` varchar(64) NOT NULL COMMENT '租户ID',
  `receipt_no` varchar(64) NOT NULL COMMENT '收款单编号',
  `customer_id` bigint(20) NOT NULL COMMENT '客户ID',
  `receipt_date` bigint(20) NOT NULL COMMENT '收款日期',
  `amount` decimal(18,2) NOT NULL COMMENT '实际收款金额',
  `written_off_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已核销金额',
  `remaining_amount` decimal(18,2) NOT NULL COMMENT '未核销收款余额',
  `receipt_type` varchar(32) NOT NULL DEFAULT 'CUSTOMER_PAYMENT' COMMENT '收款类型',
  `payment_method` varchar(32) DEFAULT NULL COMMENT '收款方式',
  `bank_account_id` bigint(20) DEFAULT NULL COMMENT '收款资金账户ID',
  `bank_transaction_no` varchar(128) DEFAULT NULL COMMENT '银行流水号或第三方交易号',
  `status` tinyint(2) NOT NULL COMMENT '0未核销，1部分核销，2已核销，3已关闭',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `del` tinyint(2) NOT NULL DEFAULT '0',
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(64) NOT NULL,
  `modify_id` varchar(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_receipt_no` (`corpid`, `receipt_no`),
  KEY `idx_receipt_customer_date` (`corpid`, `customer_id`, `receipt_date`),
  KEY `idx_receipt_customer_status` (`corpid`, `customer_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户收款开放项，含普通收款和预收';
