-- Flyway schema baseline generated from an authorized read-only export.
-- The export contains table definitions only and no business rows.

CREATE TABLE `customer` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `corpid` varchar(50) NOT NULL,
  `customer_code` varchar(64) NOT NULL,
  `customer_name` varchar(128) NOT NULL,
  `customer_short_name` varchar(128) DEFAULT NULL,
  `customer_category` varchar(32) NOT NULL,
  `region_code` varchar(32) DEFAULT NULL,
  `owner_sales_id` varchar(50) DEFAULT NULL,
  `owner_sales_name_snapshot` varchar(50) DEFAULT NULL,
  `biz_status` varchar(32) NOT NULL,
  `ref_status` varchar(32) NOT NULL,
  `default_contact_id` bigint(20) DEFAULT NULL,
  `default_address_id` bigint(20) DEFAULT NULL,
  `default_bank_account_id` bigint(20) DEFAULT NULL,
  `default_invoice_profile_id` bigint(20) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `del` tinyint(4) NOT NULL DEFAULT '0',
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(50) NOT NULL,
  `modify_id` varchar(50) NOT NULL,
  `version` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_corpid_customer_code` (`corpid`,`customer_code`),
  KEY `idx_corpid_biz_status_update_time` (`corpid`,`biz_status`,`update_time`),
  KEY `idx_corpid_ref_status_update_time` (`corpid`,`ref_status`,`update_time`),
  KEY `idx_corpid_owner_sales` (`corpid`,`owner_sales_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `customer_address` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `corpid` varchar(50) NOT NULL,
  `customer_id` bigint(20) NOT NULL,
  `address_type` varchar(32) NOT NULL,
  `receiver_name` varchar(64) DEFAULT NULL,
  `receiver_mobile` varchar(32) DEFAULT NULL,
  `province_code` varchar(32) DEFAULT NULL,
  `city_code` varchar(32) DEFAULT NULL,
  `district_code` varchar(32) DEFAULT NULL,
  `detail_address` varchar(255) NOT NULL,
  `postal_code` varchar(16) DEFAULT NULL,
  `default_flag` tinyint(4) NOT NULL DEFAULT '0',
  `biz_status` varchar(32) NOT NULL,
  `del` tinyint(4) NOT NULL DEFAULT '0',
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(50) NOT NULL,
  `modify_id` varchar(50) NOT NULL,
  `version` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_corpid_customer_id` (`corpid`,`customer_id`),
  KEY `idx_corpid_customer_default_flag` (`corpid`,`customer_id`,`default_flag`),
  KEY `idx_corpid_address_type` (`corpid`,`address_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `customer_bank_account` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `corpid` varchar(50) NOT NULL,
  `customer_id` bigint(20) NOT NULL,
  `account_name` varchar(128) NOT NULL,
  `bank_name` varchar(128) NOT NULL,
  `account_no` varchar(64) NOT NULL,
  `account_usage` varchar(64) DEFAULT NULL,
  `default_flag` tinyint(4) NOT NULL DEFAULT '0',
  `biz_status` varchar(32) NOT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `del` tinyint(4) NOT NULL DEFAULT '0',
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(50) NOT NULL,
  `modify_id` varchar(50) NOT NULL,
  `version` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_corpid_customer_id` (`corpid`,`customer_id`),
  KEY `idx_corpid_customer_default_flag` (`corpid`,`customer_id`,`default_flag`),
  KEY `idx_corpid_account_no` (`corpid`,`account_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `customer_contact` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `corpid` varchar(50) NOT NULL,
  `customer_id` bigint(20) NOT NULL,
  `contact_name` varchar(64) NOT NULL,
  `mobile` varchar(32) DEFAULT NULL,
  `phone` varchar(32) DEFAULT NULL,
  `email` varchar(128) DEFAULT NULL,
  `position_name` varchar(64) DEFAULT NULL,
  `default_flag` tinyint(4) NOT NULL DEFAULT '0',
  `biz_status` varchar(32) NOT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `del` tinyint(4) NOT NULL DEFAULT '0',
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(50) NOT NULL,
  `modify_id` varchar(50) NOT NULL,
  `version` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_corpid_customer_id` (`corpid`,`customer_id`),
  KEY `idx_corpid_customer_default_flag` (`corpid`,`customer_id`,`default_flag`),
  KEY `idx_corpid_mobile` (`corpid`,`mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `customer_invoice_profile` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `corpid` varchar(50) NOT NULL,
  `customer_id` bigint(20) NOT NULL,
  `invoice_title` varchar(128) NOT NULL,
  `tax_no` varchar(64) NOT NULL,
  `address_phone` varchar(128) DEFAULT NULL,
  `bank_name` varchar(128) DEFAULT NULL,
  `bank_account_no` varchar(64) DEFAULT NULL,
  `default_flag` tinyint(4) NOT NULL DEFAULT '0',
  `biz_status` varchar(32) NOT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `del` tinyint(4) NOT NULL DEFAULT '0',
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(50) NOT NULL,
  `modify_id` varchar(50) NOT NULL,
  `version` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_corpid_customer_id` (`corpid`,`customer_id`),
  KEY `idx_corpid_customer_default_flag` (`corpid`,`customer_id`,`default_flag`),
  KEY `idx_corpid_tax_no` (`corpid`,`tax_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `product_sku` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `spu_id` bigint(20) NOT NULL COMMENT '所属SPU ID',
  `sku_code` varchar(64) NOT NULL COMMENT 'SKU编码',
  `sku_name` varchar(256) NOT NULL COMMENT 'SKU名称',
  `mnemonic_code` varchar(64) DEFAULT NULL COMMENT '助记码',
  `main_barcode` varchar(64) DEFAULT NULL COMMENT '主条码',
  `spec_signature` varchar(256) DEFAULT NULL COMMENT '规格签名',
  `spec_snapshot` text COMMENT '规格快照JSON',
  `can_purchase` tinyint(4) NOT NULL DEFAULT '1' COMMENT '是否可采购',
  `can_sale` tinyint(4) NOT NULL DEFAULT '1' COMMENT '是否可销售',
  `can_inventory` tinyint(4) NOT NULL DEFAULT '1' COMMENT '是否可库存',
  `can_produce` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否可生产',
  `enable_status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '启用状态：0停用，1启用，2归档',
  `listing_status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '上下架状态：0下架，1上架',
  `archive_status` tinyint(4) NOT NULL DEFAULT '0',
  `weight` decimal(18,6) DEFAULT NULL COMMENT '重量',
  `volume` decimal(18,6) DEFAULT NULL COMMENT '体积',
  `ext_json` text COMMENT '轻量扩展字段',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除标记',
  `add_time` bigint(20) NOT NULL COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL COMMENT '更新时间',
  `creator_id` varchar(64) NOT NULL COMMENT '创建人',
  `modify_id` varchar(64) NOT NULL COMMENT '修改人',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku_code` (`corpid`,`sku_code`,`del`),
  UNIQUE KEY `uk_sku_barcode` (`corpid`,`main_barcode`,`del`),
  UNIQUE KEY `uk_spu_spec_signature` (`corpid`,`spu_id`,`spec_signature`,`del`),
  KEY `idx_sku_spu` (`corpid`,`spu_id`,`del`),
  KEY `idx_sku_status` (`corpid`,`enable_status`,`del`),
  KEY `idx_sku_listing` (`corpid`,`listing_status`,`del`),
  KEY `idx_sku_purchase` (`corpid`,`can_purchase`,`enable_status`,`del`),
  KEY `idx_sku_sale` (`corpid`,`can_sale`,`listing_status`,`enable_status`,`del`),
  KEY `idx_sku_inventory` (`corpid`,`can_inventory`,`enable_status`,`del`),
  KEY `idx_sku_produce` (`corpid`,`can_produce`,`enable_status`,`del`),
  KEY `idx_sku_mnemonic` (`corpid`,`mnemonic_code`,`del`),
  KEY `idx_product_sku_archive` (`corpid`,`archive_status`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品SKU主档表';
CREATE TABLE `product_sku_supplier_rel` (
  `id` bigint(20) NOT NULL,
  `corpid` varchar(50) NOT NULL,
  `sku_id` bigint(20) NOT NULL,
  `supplier_id` bigint(20) NOT NULL,
  `purchase_price` decimal(18,6) DEFAULT NULL,
  `delivery_cycle_day` int(11) DEFAULT NULL,
  `min_order_qty` decimal(18,6) DEFAULT NULL,
  `supplier_sku_code` varchar(64) DEFAULT NULL,
  `default_flag` tinyint(4) NOT NULL DEFAULT '0',
  `enable_status` tinyint(4) NOT NULL DEFAULT '1',
  `remark` varchar(500) DEFAULT NULL,
  `version` int(11) NOT NULL DEFAULT '0',
  `del` tinyint(4) NOT NULL DEFAULT '0',
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(50) NOT NULL,
  `modify_id` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku_supplier_rel_unique` (`corpid`,`sku_id`,`supplier_id`,`del`),
  KEY `idx_sku_supplier_rel_sku` (`corpid`,`sku_id`,`enable_status`,`del`),
  KEY `idx_sku_supplier_rel_supplier` (`corpid`,`supplier_id`,`enable_status`,`del`),
  KEY `idx_sku_supplier_rel_default` (`corpid`,`sku_id`,`default_flag`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `product_sku_supplier_rel_history` (
  `id` bigint(20) NOT NULL,
  `corpid` varchar(50) NOT NULL,
  `relation_id` bigint(20) NOT NULL,
  `operate_type` varchar(64) NOT NULL,
  `operator_id` varchar(50) DEFAULT NULL,
  `change_snapshot` text,
  `remark` varchar(500) DEFAULT NULL,
  `del` tinyint(4) NOT NULL DEFAULT '0',
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(50) NOT NULL,
  `modify_id` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sku_supplier_rel_history_relation` (`corpid`,`relation_id`,`del`),
  KEY `idx_sku_supplier_rel_history_type` (`corpid`,`operate_type`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `product_spu` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `spu_code` varchar(64) NOT NULL COMMENT 'SPU编码',
  `spu_name` varchar(256) NOT NULL COMMENT 'SPU名称',
  `category_id` bigint(20) NOT NULL COMMENT '分类ID',
  `brand_id` bigint(20) DEFAULT NULL COMMENT '品牌ID',
  `product_type` varchar(32) NOT NULL COMMENT '产品类型：RAW_MATERIAL/SEMI_FINISHED/FINISHED_GOOD/GOODS/SERVICE/VIRTUAL',
  `enable_spec` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否启用多规格',
  `description` varchar(1024) DEFAULT NULL COMMENT '描述',
  `image_url` varchar(512) DEFAULT NULL COMMENT '主图URL',
  `enable_status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '启用状态：0停用，1启用，2归档',
  `archive_status` tinyint(4) NOT NULL DEFAULT '0',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除标记',
  `add_time` bigint(20) NOT NULL COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL COMMENT '更新时间',
  `creator_id` varchar(64) NOT NULL COMMENT '创建人',
  `modify_id` varchar(64) NOT NULL COMMENT '修改人',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_spu_code` (`corpid`,`spu_code`,`del`),
  KEY `idx_spu_category` (`corpid`,`category_id`,`del`),
  KEY `idx_spu_brand` (`corpid`,`brand_id`,`del`),
  KEY `idx_spu_type` (`corpid`,`product_type`,`del`),
  KEY `idx_spu_status` (`corpid`,`enable_status`,`del`),
  KEY `idx_product_spu_archive` (`corpid`,`archive_status`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品SPU主档表';
CREATE TABLE `purchase_order` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `purchase_org_id` bigint(20) NOT NULL COMMENT '采购组织ID',
  `order_no` varchar(64) NOT NULL COMMENT '订单号',
  `vendor_id` bigint(20) NOT NULL COMMENT '供应商ID',
  `vendor_name_snapshot` varchar(128) NOT NULL COMMENT '供应商名称快照',
  `purchaser_id` varchar(50) DEFAULT NULL COMMENT '采购员ID',
  `purchaser_name_snapshot` varchar(50) DEFAULT NULL COMMENT '采购员名称快照',
  `warehouse_id` bigint(20) DEFAULT NULL COMMENT '默认收货仓库ID',
  `warehouse_name_snapshot` varchar(128) DEFAULT NULL COMMENT '仓库名称快照',
  `settlement_method_id` bigint(20) DEFAULT NULL COMMENT '结算方式ID',
  `settlement_method_snapshot` varchar(128) DEFAULT NULL COMMENT '结算方式快照',
  `payment_term_snapshot` varchar(255) DEFAULT NULL COMMENT '付款条件快照',
  `currency_code` varchar(16) NOT NULL COMMENT '币种',
  `delivery_date` bigint(20) DEFAULT NULL COMMENT '交货日期',
  `source_type` varchar(32) DEFAULT NULL COMMENT '来源类型',
  `source_no` varchar(64) DEFAULT NULL COMMENT '来源单号',
  `sales_linked_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否以销定购',
  `biz_status` varchar(32) NOT NULL COMMENT '业务状态',
  `approval_status` varchar(32) NOT NULL COMMENT '审批状态',
  `execution_status` varchar(32) NOT NULL COMMENT '执行状态',
  `receipt_status` varchar(32) NOT NULL COMMENT '收料状态',
  `inbound_status` varchar(32) NOT NULL COMMENT '入库状态',
  `payable_status` varchar(32) NOT NULL COMMENT '应付状态',
  `invoice_status` varchar(32) NOT NULL COMMENT '收票状态',
  `payment_status` varchar(32) NOT NULL COMMENT '付款状态',
  `gross_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '含税金额',
  `net_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '未税金额',
  `tax_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '税额',
  `inbounded_qty_summary` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已入库数量摘要',
  `uninbounded_qty_summary` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '未入库数量摘要',
  `closed_qty_summary` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已关闭数量摘要',
  `payable_amount_summary` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已确认应付金额',
  `paid_amount_summary` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已付金额',
  `invoiced_amount_summary` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已收票金额',
  `last_inbound_time` bigint(20) DEFAULT NULL COMMENT '最近入库时间',
  `last_payable_time` bigint(20) DEFAULT NULL COMMENT '最近应付确认时间',
  `period_locked_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '期间锁定标志',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_order_no` (`corpid`,`order_no`,`del`),
  KEY `idx_purchase_order_vendor` (`corpid`,`vendor_id`,`del`),
  KEY `idx_purchase_order_org_status` (`corpid`,`purchase_org_id`,`biz_status`,`approval_status`,`execution_status`,`del`),
  KEY `idx_purchase_order_finance_status` (`corpid`,`payable_status`,`invoice_status`,`payment_status`,`del`),
  KEY `idx_purchase_order_delivery` (`corpid`,`delivery_date`,`del`),
  KEY `idx_purchase_order_time` (`corpid`,`add_time`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购订单头表';
CREATE TABLE `purchase_order_item` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `order_id` bigint(20) NOT NULL COMMENT '订单头ID',
  `line_no` int(11) NOT NULL COMMENT '行号',
  `sku_id` bigint(20) NOT NULL COMMENT 'SKU ID',
  `sku_code_snapshot` varchar(64) NOT NULL COMMENT 'SKU编码快照',
  `sku_name_snapshot` varchar(128) NOT NULL COMMENT 'SKU名称快照',
  `spec_snapshot` varchar(255) DEFAULT NULL COMMENT '规格快照',
  `purchase_unit_id` bigint(20) NOT NULL COMMENT '采购单位ID',
  `warehouse_id` bigint(20) DEFAULT NULL COMMENT '行级收货仓库ID',
  `order_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '订单数量',
  `received_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已收料数量',
  `inbounded_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已入库数量',
  `closed_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已关闭数量',
  `returned_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已退料数量',
  `gross_price` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '含税单价',
  `net_price` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '未税单价',
  `tax_rate` decimal(8,4) NOT NULL DEFAULT '0.0000' COMMENT '税率',
  `tax_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '税额',
  `gross_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '含税金额',
  `net_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '未税金额',
  `payable_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已确认应付金额',
  `paid_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已付金额',
  `invoiced_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已收票金额',
  `is_gift` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否赠品',
  `delivery_plan_snapshot` varchar(500) DEFAULT NULL COMMENT '交货计划快照',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_order_line` (`order_id`,`line_no`,`del`),
  KEY `idx_purchase_order_item_sku` (`corpid`,`sku_id`,`del`),
  KEY `idx_purchase_order_item_exec` (`corpid`,`order_id`,`inbounded_qty`,`closed_qty`,`del`),
  KEY `idx_purchase_order_item_wh` (`corpid`,`warehouse_id`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购订单行表';
CREATE TABLE `purchase_pending_task` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `purchase_org_id` bigint(20) NOT NULL COMMENT '采购组织ID',
  `task_no` varchar(64) NOT NULL COMMENT '任务号',
  `source_type` varchar(32) NOT NULL COMMENT '来源类型',
  `source_doc_id` bigint(20) DEFAULT NULL COMMENT '来源单据ID',
  `source_line_id` bigint(20) DEFAULT NULL COMMENT '来源行ID',
  `source_doc_no` varchar(64) DEFAULT NULL COMMENT '来源单号快照',
  `sku_id` bigint(20) NOT NULL COMMENT 'SKU ID',
  `sku_code_snapshot` varchar(64) NOT NULL COMMENT 'SKU编码快照',
  `sku_name_snapshot` varchar(128) NOT NULL COMMENT 'SKU名称快照',
  `need_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '需求数量',
  `occupied_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已占用数量',
  `generated_request_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已生成申请数量',
  `generated_order_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已生成订单数量',
  `closed_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已关闭数量',
  `suggested_vendor_id` bigint(20) DEFAULT NULL COMMENT '建议供应商ID',
  `suggested_delivery_date` bigint(20) DEFAULT NULL COMMENT '建议交期',
  `priority_level` int(11) NOT NULL DEFAULT '0' COMMENT '优先级',
  `task_status` varchar(32) NOT NULL COMMENT '任务状态',
  `sales_linked_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否以销定购挂钩',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pending_task_no` (`corpid`,`task_no`,`del`),
  KEY `idx_pending_source` (`corpid`,`source_type`,`source_doc_id`,`source_line_id`,`del`),
  KEY `idx_pending_workbench` (`corpid`,`purchase_org_id`,`task_status`,`priority_level`,`del`),
  KEY `idx_pending_sku` (`corpid`,`sku_id`,`task_status`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='待采购任务表';
CREATE TABLE `purchase_request` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `purchase_org_id` bigint(20) NOT NULL COMMENT '采购组织ID',
  `request_no` varchar(64) NOT NULL COMMENT '申请单号',
  `request_dept_id` bigint(20) DEFAULT NULL COMMENT '申请部门ID',
  `applicant_id` varchar(50) DEFAULT NULL COMMENT '申请人ID',
  `source_type` varchar(32) NOT NULL COMMENT '需求来源类型',
  `source_no` varchar(64) DEFAULT NULL COMMENT '来源单号',
  `suggested_vendor_id` bigint(20) DEFAULT NULL COMMENT '建议供应商ID',
  `suggested_delivery_date` bigint(20) DEFAULT NULL COMMENT '建议交期',
  `biz_status` varchar(32) NOT NULL COMMENT '业务状态',
  `approval_status` varchar(32) NOT NULL COMMENT '审批状态',
  `gross_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '估算含税金额',
  `net_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '估算未税金额',
  `tax_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '估算税额',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_request_no` (`corpid`,`request_no`,`del`),
  KEY `idx_request_org_status` (`corpid`,`purchase_org_id`,`biz_status`,`approval_status`,`del`),
  KEY `idx_request_source` (`corpid`,`source_type`,`source_no`,`del`),
  KEY `idx_request_time` (`corpid`,`add_time`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购申请单头表';
CREATE TABLE `purchase_request_item` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `request_id` bigint(20) NOT NULL COMMENT '申请单头ID',
  `line_no` int(11) NOT NULL COMMENT '行号',
  `sku_id` bigint(20) NOT NULL COMMENT 'SKU ID',
  `sku_code_snapshot` varchar(64) NOT NULL COMMENT 'SKU编码快照',
  `sku_name_snapshot` varchar(128) NOT NULL COMMENT 'SKU名称快照',
  `spec_snapshot` varchar(255) DEFAULT NULL COMMENT '规格快照',
  `purchase_unit_id` bigint(20) NOT NULL COMMENT '采购单位ID',
  `request_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '申请数量',
  `reserved_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已占用下推量',
  `executed_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已正式下推量',
  `closed_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已关闭量',
  `suggested_vendor_id` bigint(20) DEFAULT NULL COMMENT '建议供应商ID',
  `suggested_delivery_date` bigint(20) DEFAULT NULL COMMENT '建议交期',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_request_line` (`request_id`,`line_no`,`del`),
  KEY `idx_request_item_sku` (`corpid`,`sku_id`,`del`),
  KEY `idx_request_item_qty` (`corpid`,`request_id`,`reserved_qty`,`executed_qty`,`closed_qty`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购申请单行表';
CREATE TABLE `purchase_source_relation` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `source_doc_type` varchar(32) NOT NULL COMMENT '来源单据类型',
  `source_doc_id` bigint(20) NOT NULL COMMENT '来源单据ID',
  `source_line_id` bigint(20) DEFAULT NULL COMMENT '来源行ID',
  `target_doc_type` varchar(32) NOT NULL COMMENT '目标单据类型',
  `target_doc_id` bigint(20) NOT NULL COMMENT '目标单据ID',
  `target_line_id` bigint(20) DEFAULT NULL COMMENT '目标行ID',
  `source_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '来源总量',
  `reserved_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已占用量',
  `executed_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已执行量',
  `closed_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已关闭量',
  `reversed_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '已逆向回退量',
  `relation_status` varchar(32) NOT NULL COMMENT '关系状态',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_source_target` (`corpid`,`source_line_id`,`target_line_id`,`target_doc_type`,`del`),
  KEY `idx_purchase_source_doc` (`corpid`,`source_doc_type`,`source_doc_id`,`source_line_id`,`del`),
  KEY `idx_purchase_target_doc` (`corpid`,`target_doc_type`,`target_doc_id`,`target_line_id`,`del`),
  KEY `idx_purchase_relation_status` (`corpid`,`relation_status`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购来源关系表';
CREATE TABLE `supplier` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `supplier_code` varchar(64) NOT NULL COMMENT '供应商编码',
  `supplier_name` varchar(128) NOT NULL COMMENT '供应商名称',
  `supplier_short_name` varchar(128) DEFAULT NULL COMMENT '供应商简称',
  `supplier_category` varchar(32) NOT NULL COMMENT '供应商分类',
  `main_business_category` varchar(64) DEFAULT NULL COMMENT '主营品类',
  `owner_purchaser_id` varchar(50) DEFAULT NULL COMMENT '归属采购ID',
  `owner_purchaser_name_snapshot` varchar(50) DEFAULT NULL COMMENT '归属采购名称快照',
  `biz_status` varchar(32) NOT NULL COMMENT '业务状态',
  `ref_status` varchar(32) NOT NULL COMMENT '引用状态摘要',
  `default_contact_id` bigint(20) DEFAULT NULL COMMENT '默认联系人ID',
  `default_address_id` bigint(20) DEFAULT NULL COMMENT '默认地址ID',
  `default_bank_account_id` bigint(20) DEFAULT NULL COMMENT '默认银行账户ID',
  `default_invoice_profile_id` bigint(20) DEFAULT NULL COMMENT '默认开票信息ID',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_corpid_supplier_code` (`corpid`,`supplier_code`),
  UNIQUE KEY `uk_corpid_supplier_name` (`corpid`,`supplier_name`),
  KEY `idx_corpid_biz_status_update_time` (`corpid`,`biz_status`,`update_time`),
  KEY `idx_corpid_ref_status_update_time` (`corpid`,`ref_status`,`update_time`),
  KEY `idx_corpid_owner_purchaser` (`corpid`,`owner_purchaser_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商主档表';
CREATE TABLE `supplier_address` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `supplier_id` bigint(20) NOT NULL COMMENT '供应商ID',
  `address_type` varchar(32) NOT NULL COMMENT '地址类型',
  `receiver_name` varchar(64) DEFAULT NULL COMMENT '收件人',
  `receiver_mobile` varchar(32) DEFAULT NULL COMMENT '联系电话',
  `province_code` varchar(32) DEFAULT NULL COMMENT '省编码',
  `city_code` varchar(32) DEFAULT NULL COMMENT '市编码',
  `district_code` varchar(32) DEFAULT NULL COMMENT '区编码',
  `detail_address` varchar(255) NOT NULL COMMENT '详细地址',
  `postal_code` varchar(16) DEFAULT NULL COMMENT '邮编',
  `default_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '默认标记',
  `biz_status` varchar(32) NOT NULL COMMENT '业务状态',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_corpid_supplier_id` (`corpid`,`supplier_id`),
  KEY `idx_corpid_supplier_default_flag` (`corpid`,`supplier_id`,`default_flag`),
  KEY `idx_corpid_address_type` (`corpid`,`address_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商地址表';
CREATE TABLE `supplier_attachment_relation` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `supplier_id` bigint(20) NOT NULL COMMENT '供应商ID',
  `file_id` bigint(20) NOT NULL COMMENT '附件ID',
  `attachment_type` varchar(32) NOT NULL COMMENT '附件类型',
  `attachment_name_snapshot` varchar(128) DEFAULT NULL COMMENT '附件名称快照',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `biz_status` varchar(32) NOT NULL COMMENT '业务状态',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_corpid_supplier_id` (`corpid`,`supplier_id`),
  KEY `idx_corpid_file_id` (`corpid`,`file_id`),
  KEY `idx_corpid_attachment_type` (`corpid`,`attachment_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商附件关联表';
CREATE TABLE `supplier_bank_account` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `supplier_id` bigint(20) NOT NULL COMMENT '供应商ID',
  `account_name` varchar(128) NOT NULL COMMENT '账户名称',
  `bank_name` varchar(128) NOT NULL COMMENT '开户行',
  `bank_account_no` varchar(64) NOT NULL COMMENT '银行账号',
  `account_usage` varchar(32) DEFAULT NULL COMMENT '账户用途',
  `default_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '默认标记',
  `biz_status` varchar(32) NOT NULL COMMENT '业务状态',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_corpid_supplier_id` (`corpid`,`supplier_id`),
  KEY `idx_corpid_supplier_default_flag` (`corpid`,`supplier_id`,`default_flag`),
  KEY `idx_corpid_bank_account_no` (`corpid`,`bank_account_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商银行账户表';
CREATE TABLE `supplier_contact` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `supplier_id` bigint(20) NOT NULL COMMENT '供应商ID',
  `contact_name` varchar(64) NOT NULL COMMENT '联系人姓名',
  `mobile` varchar(32) DEFAULT NULL COMMENT '手机号',
  `phone` varchar(32) DEFAULT NULL COMMENT '电话',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱',
  `position_name` varchar(64) DEFAULT NULL COMMENT '职位',
  `default_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '默认标记',
  `biz_status` varchar(32) NOT NULL COMMENT '业务状态',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_corpid_supplier_id` (`corpid`,`supplier_id`),
  KEY `idx_corpid_supplier_default_flag` (`corpid`,`supplier_id`,`default_flag`),
  KEY `idx_corpid_mobile` (`corpid`,`mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商联系人表';
CREATE TABLE `supplier_idempotent_record` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `idempotent_no` varchar(64) NOT NULL COMMENT '幂等号',
  `biz_type` varchar(32) NOT NULL COMMENT '业务类型',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '业务ID',
  `request_json` text COMMENT '请求报文',
  `response_json` text COMMENT '响应报文',
  `process_status` varchar(32) NOT NULL COMMENT '处理状态',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_corpid_idempotent_no` (`corpid`,`idempotent_no`),
  KEY `idx_corpid_biz_type_biz_id` (`corpid`,`biz_type`,`biz_id`),
  KEY `idx_corpid_process_status` (`corpid`,`process_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商幂等记录表';
CREATE TABLE `supplier_invoice_profile` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `supplier_id` bigint(20) NOT NULL COMMENT '供应商ID',
  `invoice_title` varchar(128) NOT NULL COMMENT '开票抬头',
  `tax_no` varchar(64) NOT NULL COMMENT '税号',
  `address_phone` varchar(64) DEFAULT NULL COMMENT '地址电话',
  `bank_name` varchar(128) DEFAULT NULL COMMENT '开户行',
  `bank_account_no` varchar(64) DEFAULT NULL COMMENT '银行账号',
  `default_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '默认标记',
  `biz_status` varchar(32) NOT NULL COMMENT '业务状态',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_corpid_supplier_id` (`corpid`,`supplier_id`),
  KEY `idx_corpid_supplier_default_flag` (`corpid`,`supplier_id`,`default_flag`),
  KEY `idx_corpid_tax_no` (`corpid`,`tax_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商开票信息表';
CREATE TABLE `supplier_operate_log` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `supplier_id` bigint(20) NOT NULL COMMENT '供应商ID',
  `operate_type` varchar(32) NOT NULL COMMENT '操作类型',
  `target_type` varchar(32) NOT NULL COMMENT '目标类型',
  `target_id` bigint(20) DEFAULT NULL COMMENT '目标ID',
  `before_json` text COMMENT '变更前快照',
  `after_json` text COMMENT '变更后快照',
  `operator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '操作人ID',
  `operator_name_snapshot` varchar(50) DEFAULT NULL COMMENT '操作人名称快照',
  `operate_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '操作时间',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_corpid_supplier_id` (`corpid`,`supplier_id`),
  KEY `idx_corpid_operate_time` (`corpid`,`operate_time`),
  KEY `idx_corpid_operate_type` (`corpid`,`operate_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商操作流水表';
CREATE TABLE `supplier_reference_summary` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `supplier_id` bigint(20) NOT NULL COMMENT '供应商ID',
  `purchase_ref_count` bigint(20) NOT NULL DEFAULT '0' COMMENT '采购引用次数',
  `payable_ref_count` bigint(20) NOT NULL DEFAULT '0' COMMENT '应付引用次数',
  `payment_ref_count` bigint(20) NOT NULL DEFAULT '0' COMMENT '付款引用次数',
  `invoice_ref_count` bigint(20) NOT NULL DEFAULT '0' COMMENT '发票引用次数',
  `reconcile_ref_count` bigint(20) NOT NULL DEFAULT '0' COMMENT '对账引用次数',
  `active_flow_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '进行中引用标记',
  `last_ref_time` bigint(20) DEFAULT NULL COMMENT '最近引用时间',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_corpid_supplier_id` (`corpid`,`supplier_id`),
  KEY `idx_corpid_active_flow_flag` (`corpid`,`active_flow_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商引用摘要表';
CREATE TABLE `sys_department` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `department_code` varchar(50) NOT NULL COMMENT '部门编码',
  `department_name` varchar(100) NOT NULL COMMENT '部门名称',
  `parent_id` bigint(20) DEFAULT NULL COMMENT '父部门ID',
  `ancestor_path` varchar(1000) NOT NULL COMMENT '祖先路径',
  `department_level` int(11) NOT NULL DEFAULT '1' COMMENT '部门层级',
  `leader_user_id` bigint(20) DEFAULT NULL COMMENT '负责人员工ID',
  `sort_no` int(11) NOT NULL DEFAULT '0' COMMENT '排序值',
  `department_status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态，1=启用，0=停用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_corpid_department_code` (`corpid`,`department_code`,`del`),
  KEY `idx_corpid_parent_id` (`corpid`,`parent_id`,`del`),
  KEY `idx_corpid_ancestor_path` (`corpid`,`ancestor_path`(255),`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='部门表';
CREATE TABLE `sys_menu` (
  `id` bigint(20) NOT NULL,
  `corpid` varchar(50) COLLATE utf8mb4_bin NOT NULL,
  `menu_code` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  `menu_name` varchar(128) COLLATE utf8mb4_bin NOT NULL,
  `surface` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `parent_menu_id` bigint(20) DEFAULT NULL,
  `menu_type` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `route_path` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `component_path` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `icon` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL,
  `sort_no` int(11) NOT NULL DEFAULT '0',
  `pinned_home` tinyint(4) NOT NULL DEFAULT '0',
  `enable_status` tinyint(4) NOT NULL DEFAULT '1',
  `del` tinyint(4) NOT NULL DEFAULT '0',
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  `modify_id` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_menu_code` (`corpid`,`menu_code`,`del`),
  KEY `idx_sys_menu_surface` (`corpid`,`surface`,`del`),
  KEY `idx_sys_menu_parent` (`corpid`,`surface`,`parent_menu_id`,`del`),
  KEY `idx_sys_menu_status` (`corpid`,`surface`,`enable_status`,`del`),
  KEY `idx_sys_menu_sort` (`corpid`,`surface`,`sort_no`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `sys_permission` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `parent_id` bigint(20) NOT NULL DEFAULT '0',
  `permission_code` varchar(100) NOT NULL COMMENT '权限编码',
  `permission_name` varchar(100) NOT NULL COMMENT '权限名称',
  `permission_type` varchar(20) NOT NULL COMMENT '权限类型，MENU/ACTION',
  `menu_alias` varchar(100) DEFAULT NULL COMMENT '菜单别名',
  `action_code` varchar(100) DEFAULT NULL COMMENT '操作编码',
  `data_scope_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否支持数据权限，1=支持，0=不支持',
  `permission_status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态，1=启用，0=停用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_permission_code` (`permission_code`,`del`),
  KEY `idx_permission_menu_alias` (`menu_alias`,`del`),
  KEY `idx_parent_id` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权限点字典表';
CREATE TABLE `sys_role` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `role_name` varchar(100) NOT NULL COMMENT '角色名称',
  `role_type` varchar(20) NOT NULL DEFAULT 'CUSTOM' COMMENT '角色类型，SYSTEM/CUSTOM',
  `role_status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态，1=启用，0=停用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  KEY `idx_corpid_role_name` (`corpid`,`role_name`,`del`),
  KEY `idx_corpid_role_status` (`corpid`,`role_status`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色表';
CREATE TABLE `sys_role_permission_data_scope` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `role_id` bigint(20) NOT NULL COMMENT '角色ID',
  `permission_id` bigint(20) NOT NULL COMMENT '菜单权限ID',
  `data_scope_type` varchar(30) NOT NULL COMMENT '数据权限范围，SELF/DEPT/DEPT_AND_CHILD/ALL',
  `rel_status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态，1=启用，0=停用',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_corpid_role_permission_scope` (`corpid`,`role_id`,`permission_id`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色菜单数据权限表';
CREATE TABLE `sys_role_permission_rel` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `role_id` bigint(20) NOT NULL COMMENT '角色ID',
  `permission_id` bigint(20) NOT NULL COMMENT '权限ID',
  `rel_status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '关系状态，1=启用，0=停用',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_corpid_role_permission` (`corpid`,`role_id`,`permission_id`,`del`),
  KEY `idx_corpid_permission_id` (`corpid`,`permission_id`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色权限关系表';
CREATE TABLE `sys_user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `user_id` varchar(50) NOT NULL COMMENT '员工id',
  `account_id` bigint(20) DEFAULT NULL COMMENT '关联登录账号ID',
  `user_code` varchar(50) NOT NULL COMMENT '员工编码',
  `user_name` varchar(100) NOT NULL COMMENT '员工姓名',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `job_no` varchar(50) DEFAULT NULL COMMENT '工号',
  `main_department_id` bigint(20) NOT NULL COMMENT '主部门ID',
  `user_status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '员工状态，1=启用，0=停用',
  `employment_status` varchar(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '任职状态，ACTIVE/RESIGNED',
  `entry_time` bigint(20) DEFAULT NULL COMMENT '入职时间',
  `resigned_time` bigint(20) DEFAULT NULL COMMENT '离职时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_corpid_user_code` (`corpid`,`user_code`,`del`),
  KEY `idx_corpid_account_id` (`corpid`,`account_id`,`del`),
  KEY `idx_corpid_main_department_employment` (`corpid`,`main_department_id`,`employment_status`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工表';
CREATE TABLE `sys_user_account` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `login_name` varchar(100) NOT NULL COMMENT '登录账号',
  `password_hash` varchar(255) NOT NULL COMMENT '密码摘要',
  `password_salt` varchar(100) NOT NULL COMMENT '密码盐值',
  `mobile` varchar(20) DEFAULT NULL COMMENT '绑定手机号',
  `mobile_bind_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '手机是否已绑定',
  `mobile_bind_time` bigint(20) DEFAULT NULL COMMENT '手机绑定时间',
  `account_status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '账号状态，1=启用，0=停用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_login_name` (`login_name`,`del`),
  UNIQUE KEY `uk_mobile` (`mobile`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='登录账号表';
CREATE TABLE `sys_user_department_rel` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `user_id` varchar(50) NOT NULL COMMENT '员工ID',
  `department_id` bigint(20) NOT NULL COMMENT '部门ID',
  `main_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否主部门，1=是，0=否',
  `rel_status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '关系状态，1=启用，0=停用',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`,`user_id`) USING BTREE,
  UNIQUE KEY `uk_corpid_user_department` (`corpid`,`user_id`,`department_id`,`del`),
  KEY `idx_corpid_department_id` (`corpid`,`department_id`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工部门关系表';
CREATE TABLE `sys_user_role_rel` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `user_id` varchar(50) NOT NULL COMMENT '员工ID',
  `role_id` bigint(20) NOT NULL COMMENT '角色ID',
  `rel_status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '关系状态，1=启用，0=停用',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`,`user_id`) USING BTREE,
  UNIQUE KEY `uk_corpid_user_role` (`corpid`,`user_id`,`role_id`,`del`),
  KEY `idx_corpid_role_id` (`corpid`,`role_id`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工角色关系表';


