CREATE TABLE `receivable` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `corpid` varchar(64) NOT NULL COMMENT '租户ID',
    `receivable_no` varchar(64) NOT NULL COMMENT '应收开放项编号',
    `customer_id` bigint(20) NOT NULL COMMENT '客户ID',
    `source_type` varchar(32) NOT NULL COMMENT '来源：SALES_INVOICE、OPENING_BALANCE、MANUAL_ADJUSTMENT',
    `source_invoice_id` bigint(20) DEFAULT NULL COMMENT '来源销售发票ID',
    `opening_batch_id` bigint(20) DEFAULT NULL COMMENT '期初导入批次ID',
    `receivable_date` bigint(20) NOT NULL COMMENT '应收确认日期',
    `due_date` bigint(20) DEFAULT NULL COMMENT '到期日',
    `amount` decimal(18, 2) NOT NULL COMMENT '初始应收金额',
    `written_off_amount` decimal(18, 2) NOT NULL DEFAULT '0.00' COMMENT '已核销金额',
    `remaining_amount` decimal(18, 2) NOT NULL COMMENT '未核销应收余额',
    `status` tinyint(2) NOT NULL COMMENT '状态：未核销、部分核销、已核销、已关闭',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `del` tinyint(2) NOT NULL DEFAULT '0',
    `add_time` bigint(20) NOT NULL,
    `update_time` bigint(20) NOT NULL,
    `creator_id` varchar(64) NOT NULL,
    `modify_id` varchar(64) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_receivable_no` (`corpid`, `receivable_no`),
    UNIQUE KEY `uk_receivable_invoice` (`corpid`, `source_invoice_id`),
    KEY `idx_receivable_customer_status` (`corpid`, `customer_id`, `status`, `due_date`),
    KEY `idx_receivable_source` (`corpid`, `source_type`, `source_invoice_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '应收开放项';
