CREATE TABLE `purchase_inbound` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `purchase_org_id` bigint(20) NOT NULL COMMENT '采购组织ID',
  `inbound_no` varchar(64) NOT NULL COMMENT '入库单号',
  `source_doc_type` varchar(32) NOT NULL COMMENT '来源单据类型',
  `source_doc_id` bigint(20) NOT NULL COMMENT '来源单据ID',
  `vendor_id` bigint(20) NOT NULL COMMENT '供应商ID',
  `warehouse_id` bigint(20) NOT NULL COMMENT '仓库ID',
  `actual_inbound_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '实际入库时间',
  `biz_status` varchar(32) NOT NULL COMMENT '业务状态',
  `approval_status` varchar(32) NOT NULL COMMENT '审批状态',
  `execution_status` varchar(32) NOT NULL COMMENT '执行状态',
  `gross_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '含税金额',
  `net_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '未税金额',
  `tax_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '税额',
  `inventory_cost_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '库存成本金额',
  `inventory_flow_no` varchar(64) DEFAULT NULL COMMENT '库存流水号',
  `payable_trigger_status` varchar(32) NOT NULL COMMENT '应付触发状态',
  `payable_no` varchar(64) DEFAULT NULL COMMENT '应付单号',
  `invoice_source_status` varchar(32) NOT NULL COMMENT '收票来源状态',
  `period_locked_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '期间锁定标记',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_inbound_no` (`corpid`,`inbound_no`,`del`),
  KEY `idx_purchase_inbound_source` (`corpid`,`source_doc_type`,`source_doc_id`,`del`),
  KEY `idx_purchase_inbound_vendor` (`corpid`,`vendor_id`,`del`),
  KEY `idx_purchase_inbound_time` (`corpid`,`actual_inbound_time`,`del`),
  KEY `idx_purchase_inbound_status` (`corpid`,`biz_status`,`execution_status`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购入库单头表';

CREATE TABLE `purchase_inbound_item` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `inbound_id` bigint(20) NOT NULL COMMENT '入库单ID',
  `line_no` int(11) NOT NULL COMMENT '行号',
  `source_line_id` bigint(20) DEFAULT NULL COMMENT '来源单据行ID',
  `sku_id` bigint(20) NOT NULL COMMENT 'SKU ID',
  `warehouse_id` bigint(20) NOT NULL COMMENT '仓库ID',
  `batch_no` varchar(64) DEFAULT NULL COMMENT '批次号',
  `serial_no` varchar(128) DEFAULT NULL COMMENT '序列号',
  `produce_date` bigint(20) DEFAULT NULL COMMENT '生产日期',
  `expire_date` bigint(20) DEFAULT NULL COMMENT '有效期至',
  `qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '入库数量',
  `qualified_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '合格数量',
  `unqualified_qty` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '不合格数量',
  `gross_price` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '含税单价',
  `net_price` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '未税单价',
  `tax_rate` decimal(8,4) NOT NULL DEFAULT '0.0000' COMMENT '税率',
  `gross_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '含税金额',
  `net_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '未税金额',
  `tax_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '税额',
  `inventory_cost_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '库存成本金额',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_inbound_line` (`inbound_id`,`line_no`,`del`),
  KEY `idx_purchase_inbound_item_source` (`corpid`,`source_line_id`,`del`),
  KEY `idx_purchase_inbound_item_sku` (`corpid`,`sku_id`,`del`),
  KEY `idx_purchase_inbound_item_batch` (`corpid`,`warehouse_id`,`sku_id`,`batch_no`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购入库单行表';

CREATE TABLE `purchase_idempotent_record` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `corpid` varchar(50) NOT NULL COMMENT '租户ID',
  `biz_type` varchar(64) NOT NULL COMMENT '业务类型',
  `idempotent_no` varchar(128) NOT NULL COMMENT '幂等号',
  `biz_key` varchar(128) NOT NULL COMMENT '业务键',
  `process_status` varchar(32) NOT NULL COMMENT '处理状态',
  `result_ref_no` varchar(128) DEFAULT NULL COMMENT '结果引用号',
  `result_payload` text COMMENT '结果快照',
  `expire_time` bigint(20) DEFAULT NULL COMMENT '失效时间',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `add_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `creator_id` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `modify_id` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_idempotent` (`corpid`,`biz_type`,`idempotent_no`,`del`),
  KEY `idx_purchase_idempotent_biz` (`corpid`,`biz_key`,`process_status`,`del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购幂等记录表';
