CREATE TABLE `purchase_invoice` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `corpid` varchar(64) NOT NULL COMMENT '租户ID',
    `invoice_no` varchar(64) NOT NULL COMMENT '采购发票编号',
    `supplier_invoice_no` varchar(128) DEFAULT NULL COMMENT '供应商发票号码',
    `supplier_id` bigint(20) NOT NULL COMMENT '供应商ID',
    `invoice_date` bigint(20) NOT NULL COMMENT '发票日期',
    `due_date` bigint(20) DEFAULT NULL COMMENT '应付到期日',
    `payment_term` varchar(64) DEFAULT NULL COMMENT '付款条件',
    `untaxed_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '未税金额',
    `tax_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '税额',
    `amount` decimal(18,2) NOT NULL COMMENT '含税总金额',
    `invoice_type` varchar(32) NOT NULL DEFAULT 'PURCHASE' COMMENT '发票类型',
    `status` varchar(32) NOT NULL COMMENT '状态',
    `audit_status` tinyint(2) NOT NULL DEFAULT '0' COMMENT '审核状态',
    `audit_time` bigint(20) DEFAULT NULL COMMENT '审核时间',
    `posted_time` bigint(20) DEFAULT NULL COMMENT '过账时间',
    `original_invoice_id` bigint(20) DEFAULT NULL COMMENT '原采购发票ID',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `del` tinyint(2) NOT NULL DEFAULT '0',
    `add_time` bigint(20) NOT NULL,
    `update_time` bigint(20) NOT NULL,
    `creator_id` varchar(64) NOT NULL,
    `modify_id` varchar(64) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_purchase_invoice_no` (`corpid`, `invoice_no`),
    KEY `idx_purchase_invoice_supplier_date` (`corpid`, `supplier_id`, `invoice_date`),
    KEY `idx_purchase_invoice_status_due_date` (`corpid`, `status`, `due_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购发票';

CREATE TABLE `payable` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `corpid` varchar(64) NOT NULL COMMENT '租户ID',
    `payable_no` varchar(64) NOT NULL COMMENT '应付开放项编号',
    `supplier_id` bigint(20) NOT NULL COMMENT '供应商ID',
    `source_type` varchar(32) NOT NULL COMMENT '来源类型',
    `source_invoice_id` bigint(20) DEFAULT NULL COMMENT '来源采购发票ID',
    `payable_date` bigint(20) NOT NULL COMMENT '应付确认日期',
    `due_date` bigint(20) DEFAULT NULL COMMENT '到期日',
    `amount` decimal(18,2) NOT NULL COMMENT '初始应付金额',
    `written_off_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已核销金额',
    `remaining_amount` decimal(18,2) NOT NULL COMMENT '未核销余额',
    `status` tinyint(2) NOT NULL COMMENT '核销状态',
    `audit_status` tinyint(2) NOT NULL DEFAULT '0' COMMENT '审核状态',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `del` tinyint(2) NOT NULL DEFAULT '0',
    `add_time` bigint(20) NOT NULL,
    `update_time` bigint(20) NOT NULL,
    `creator_id` varchar(64) NOT NULL,
    `modify_id` varchar(64) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_payable_no` (`corpid`, `payable_no`),
    UNIQUE KEY `uk_payable_invoice` (`corpid`, `source_invoice_id`),
    KEY `idx_payable_supplier_status` (`corpid`, `supplier_id`, `status`, `due_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应付开放项';

CREATE TABLE `payment` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `corpid` varchar(64) NOT NULL COMMENT '租户ID',
    `payment_no` varchar(64) NOT NULL COMMENT '付款单编号',
    `supplier_id` bigint(20) NOT NULL COMMENT '供应商ID',
    `payment_date` bigint(20) NOT NULL COMMENT '付款日期',
    `amount` decimal(18,2) NOT NULL COMMENT '实际付款金额',
    `written_off_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已核销金额',
    `remaining_amount` decimal(18,2) NOT NULL COMMENT '未核销付款余额',
    `payment_type` varchar(32) NOT NULL DEFAULT 'SUPPLIER_PAYMENT' COMMENT '付款类型',
    `payment_method` varchar(32) DEFAULT NULL COMMENT '付款方式',
    `bank_account_id` bigint(20) DEFAULT NULL COMMENT '资金账户ID',
    `bank_transaction_no` varchar(128) DEFAULT NULL COMMENT '银行或第三方交易号',
    `status` tinyint(2) NOT NULL COMMENT '核销状态',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `del` tinyint(2) NOT NULL DEFAULT '0',
    `add_time` bigint(20) NOT NULL,
    `update_time` bigint(20) NOT NULL,
    `creator_id` varchar(64) NOT NULL,
    `modify_id` varchar(64) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_payment_no` (`corpid`, `payment_no`),
    KEY `idx_payment_supplier_date` (`corpid`, `supplier_id`, `payment_date`),
    KEY `idx_payment_supplier_status` (`corpid`, `supplier_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商付款开放项';
