CREATE TABLE `purchase_order_item` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `corpid` varchar(64) NOT NULL COMMENT '租户ID',
  `purchase_order_id` bigint(20) NOT NULL,
  `line_no` int(11) NOT NULL,
  `sku_id` bigint(20) NOT NULL,
  `sku_code` varchar(64) NOT NULL,
  `sku_name` varchar(128) NOT NULL,
  `specification` varchar(128) DEFAULT NULL,
  `unit_name` varchar(32) NOT NULL,
  `qty` decimal(18,6) NOT NULL,
  `inbound_qty` decimal(18,6) NOT NULL DEFAULT '0.000000',
  `unit_price` decimal(18,6) NOT NULL,
  `tax_rate` decimal(8,4) NOT NULL DEFAULT '0.0000',
  `amount` decimal(18,2) NOT NULL,
  `del` tinyint(2) NOT NULL DEFAULT '0',
  `add_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `creator_id` varchar(64) NOT NULL,
  `modify_id` varchar(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_order_line` (`purchase_order_id`, `line_no`),
  KEY `idx_purchase_order_item_sku` (`corpid`, `sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购订单行';
