spring:
  application:
    name: xbb-erp-app-mobile
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xbb_erp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
management:
  endpoints:
    web:
      exposure:
        include: health
